language: node_js
node_js:
    - '12'
cache:
    directories:
        - node_modules
script:
    - npm t
deploy:
    provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_API_TOKEN
    on:
        tags: true
        branch: master
        repo: mjeightyfive/stylelint-config
